### PR TITLE
[oa_messages] This gets the oa_messages feature out of its overridden state.

### PR DESCRIPTION
**Pull request by scottalan**
Once again I had to update the oa_message feature to keep it from being overridden. If this looks wrong please comment so I can fix it. Thanks

### CODE REVIEW

**Comment by mike-potter** [comment]
I might commit part of this one.  The problem I have always had with the message stuff is that "message_notify_daily_digest" and "message_notify_weekly_digest" are only present if you have the message_digest module enabled.  It's one of the Drupal issues where adding a new View Mode to an entity causes it to get added everywhere.  I dislike that adding a new message or new view mode causes Features to get overridden, but have not found a good workaround.

My other worry is that if I add this to the Feature and then disable the message_digest module then it will be overridden again.

**Comment by scottalan** [comment]
ok, I can just revert modules/oa_messages/oa_messages.features.field_instance.inc if the rest of it is ok.

**Comment by scottalan** [comment]
What about this...OA installs with _message_digest_ and _oa_messages_digest_ enabled so maybe add all the features-updates concerning "message_notify_daily_digest" and "message_notify_weekly_digest", then we could do something like this: https://gist.github.com/scottalan/32a21f5aff8d42b6fc39. This would go for _oa_worktracker_ as well. It would be able to go ahead and update the field_instances in the feature to include those view modes and oa_messages would take care of the rest. Maybe this belongs in oa_core, not oa_messages? What are your thoughts? Just really wanting to get features in a clean state for those of us planning on using _features_override_ and working in a dev/prod workflow.

**Comment by mike-potter** [comment]
I think oa_messages is fine.  For now I can see using the code in your gist until we find a better way.  As you said, at least this handled the message_digest stuff.

**Comment by scottalan** [comment]
I went ahead and added the `message_notify_daily_digest` and `message_notify_weekly_digest` field instances and added the code from the above referenced gist. I've tested this and when the message_digest module is disabled the feature remains in it's default state.

**Pull request merged**
