### PR TITLE
[WORKING] oa core pane uuid updates

### PR DESCRIPTION
**Pull request by scottalan**
This is just to show the updates for `new-*` -> `uuid`.
I updated everything in the whole distro.

This is just for oa_core.

I also updated panopoly as well. @dsnopek 

Please disregard anything other than:

```
modified:   modules/oa_home/oa_home.pages_default.inc
modified:   modules/oa_layouts/oa_layouts.pages_default.inc
modified:   modules/oa_layouts/oa_layouts.panelizer.inc
modified:   modules/oa_layouts/oa_layouts.panels_default.inc
modified:   modules/oa_news/oa_news.features.inc
modified:   modules/oa_news/oa_news.panelizer.inc
modified:   modules/oa_panopoly_users/oa_panopoly_users.features.features_overrides.inc
modified:   modules/oa_panopoly_users/oa_panopoly_users.features.inc
modified:   modules/oa_panopoly_users/oa_panopoly_users.info
modified:   modules/oa_search/oa_search.pages_default.inc
modified:   modules/oa_teams/oa_teams.pages_default.inc
modified:   modules/oa_teams/oa_teams.panelizer.inc
modified:   modules/oa_users/oa_users.features.field_instance.inc
modified:   modules/oa_users/oa_users.pages_default.inc
modified:   oa_core.pages_default.inc
```

### CODE REVIEW

**Comment by dsnopek** [comment]
Cool! However, nothing should be committed to Open Atrium until this patch has been committed to Panopoly and Open Atrium has started using the latest Panopoly so that our UUIDs are in sync:

https://drupal.org/node/2188597

**Comment by scottalan** [comment]
I did sync the uuids on the Panopoly versions that are installed with OA 2.13.

**Comment by scottalan** [comment]
I actually got all features out of an overridden state with the exception of the following:

_panopoly_users_

```
Component type: info
  features[panelizer_defaults][] = user:user:default:featured
  features[variable][] = page_manager_user_view_disabled
> features[variable][] = panelizer_defaults_user_user
  features[variable][] = panelizer_user:user_allowed_layouts_default
  features[variable][] = panelizer_user:user_allowed_types_default


Component type: page_manager_handlers
        'panels_breadcrumbs_paths' => '',
        'panels_breadcrumbs_home' => 1,
>       'body_classes_to_add' => 'oa-login',
>       'body_classes_to_remove' => '',
        'display' => array(
          'args' => array(),
          'title_pane' => 0,
        ),
<       'body_classes_to_add' => 'oa-login',
<       'body_classes_to_remove' => '',
      ),
    ),
```

and the "message_notify_weekly_digest" and "message_notify_daily_digest" issue of not wanting to update those in:

```
oa_discussion
oa_messages
```

**Comment by dsnopek** [comment]
> I did sync the uuids on the Panopoly versions that are installed with OA 2.13.

Ok, if you used the patch from Panopoly that I linked above, then you should be good!

The thing is that UUIDs are unique (that's one of the U's) so if you upgraded on your computer, it'll use different UUID's than if I upgraded on my computer. But we need them to be the same UUIDs! I'm planning to take the ones in the patch that @caschbre made.

**Comment by scottalan** [comment]
I know they are unique and I know that they will be different. This is why I used the patches you referenced. This is what I used:

testing.make ->

; Override panopoly_core.make: a915408
; Patch Panels to fix issue with custom region styles (#1838544)
projects[panels][type] = module
projects[panels][subdir] = contrib
projects[panels][download][type] = git
projects[panels][download][url] = http://git.drupal.org/project/panels.git
projects[panels][download][revision] = a879ecc
projects[panels][download][branch] = 7.x-3.x
; This has been committed.
;projects[panels][patch][1354572] = http://drupal.org/files/ipe-duplicate-1354572-7.patch
projects[panels][patch][2012188] = http://drupal.org/files/panels_ipe-title-ctools-2012188-3.patch
; This has been committed.
;projects[panels][patch][2024441] = http://drupal.org/files/2024441-panels_standard_render_form_include-5.patch

; Override oa_core.make
projects[ctools][type] = module
projects[ctools][subdir] = contrib
projects[ctools][download][type] = git
projects[ctools][download][url] = http://git.drupal.org/project/ctools.git
projects[ctools][download][revision] = a333dfc
projects[ctools][download][branch] = 7.x-1.x
projects[ctools][patch][1901106] = http://drupal.org/files/1901106-ctools-views_content-exposed_form_override-13.patch
; This has been committed.
;projects[ctools][patch][2016559] = http://drupal.org/files/ctools_views_content_numeric_pager_id.patch
projects[ctools][patch][2023705] = http://drupal.org/files/2023705-ctools-autosubmit-2.patch
; Does not apply cleanly.
;projects[ctools][patch][1910608] = http://drupal.org/files/1910608-views_content-ajax-7.patch

testing.sh ->

#!/bin/bash

CORE="/Users/scott/Sites/oa/public"
CEDI="${CORE}/sites/all"
PANOPOLY="${CORE}/profiles/openatrium/modules/panopoly"

# Move to drupal core.

cd ${CORE}

# Run the make for testing upgrades to ctools latest dev.

drush make --no-cache --no-core --working-copy --contrib-destination=profiles/openatrium ${CEDI}/testing.make -y

## Apply patches at https://drupal.org/node/2188597 for panopoly: users, search, pages, core and admin.

# Panopoly Users patch.

cd ${PANOPOLY}/panopoly_users
curl https://drupal.org/files/issues/panopoly_users-chaos_upgrade-2188597-1.patch | git apply -

# Panopoly Search patch.

cd ${PANOPOLY}/panopoly_search
curl https://drupal.org/files/issues/panopoly_search-chaos_upgrade-2188597-1.patch | git apply -

# Panopoly Pages patch.

cd ${PANOPOLY}/panopoly_pages
curl https://drupal.org/files/issues/panopoly_pages-chaos_upgrade-2188597-1.patch | git apply -

# Panopoly Core patch.

cd ${PANOPOLY}/panopoly_core
curl https://drupal.org/files/issues/panopoly_core-chaos_upgrade-2188597-1.patch | git apply -

# Panopoly Admin patch.

cd ${PANOPOLY}/panopoly_admin
curl https://drupal.org/files/issues/panopoly_admin-chaos_upgrade-2188597-1.patch | git apply -

**Comment by dsnopek** [comment]
Ok, awesome! Then this shouldn't need any changes. :-) Sorry for the confusion - it wasn't immediately visible in your patch or from your description that you had used those patches from the issue queue.

Thanks again for leading on the initiative to get rid of all overridden features in Open Atrium!!

**Comment by scottalan** [comment]
Sorry, was trying to leave this comment and lost my internet connection....It's snowing heavy here.

It is possible that during the process a few may have changed. Will check on that. It was a little trickier than just updated all the features because of the overrides :)  If I am off, I'll sync them up in OA. I think most, if not all, of the uuids I'm using are different. I did start out with the patch but ended up overriding all of them during the process. My main goal was to get the overrides synced up between the distros.

**Comment by scottalan** [comment]
I updated this pull request so that oa_panopoly_users uuids will match the uuids in the patches here https://drupal.org/node/2188597

**Comment by scottalan** [comment]
Closing this in favor of #13.

**Pull request closed without merging**
