### PR TITLE
Modify the 'No results' message from trash_flag to be Open Atrium specific.

### PR DESCRIPTION
**Pull request by dsnopek**
This depends on this patch to trash_flag to add a 'No results' message in the first place:

https://www.drupal.org/node/2298879

Basically, seeing the "Archive" page empty with just a title is very confusing to new users, since they don't know what is _supposed_ to be there. This gives them an idea!

### CODE REVIEW

**Comment by dsnopek** [comment]
Hunter gave me commit rights to 'trash_flag', so #2298879 is now fixed! So, this PR is necessary to rebrand the 'No results' message to match Open Atrium (ie. Group -> Space, etc).

**Comment by dsnopek** [comment]
Er, something just occurred to me: this PR doesn't actually update 'trash_flag' to a new version with the necessary change. Should I update the PR to use the -dev version of 'trash_flag'? Or should we try to coordinate a new -beta release or something?

**Comment by mike-potter** [comment]
We should probably just coordinate a new beta release.  Let me go ahead and apply the patch to trash_flag and once it's released on drupal.org then you can update this pull request with the new trash_flag version

**Comment by mike-potter** [comment]
OK, released trash_flag 7.x-1.0-beta3.

**Comment by dsnopek** [comment]
Alright, I've updated the PR to use trash_flag 1.0-beta3!

**Comment by dsnopek** [comment]
Thanks! :-)

**Pull request merged**
