### PR TITLE
[oa_buttons] This allows the creation of more than one 'node/add' command button per section type

### PR DESCRIPTION
**Pull request by scottalan**
I ran across this when I created 3 Discussion Post sections.
Only the first Discussion Post button was added.
I'm using the title for the link and just prepending 'Create'.

### CODE REVIEW

**Comment by scottalan** [comment]
This breaks oa_worktracker. Working on a fix for it now.

**Comment by scottalan** [comment]
The fix for oa_worktracker https://drupal.org/node/2273639

**Comment by mike-potter** [comment]
I think this is close but still needs a bit of refactoring:

1) I'm not a fan of using strpos.  Could cause issues with multilingual.  Since the machine name of the command button is in the $buttons[0]['value'] array, I think you can just loop over $buttons directly instead of just looping over the keys.  Then use $button['value'] as the entity_type and for the node_access checks.

So in oa_buttons_get_command_buttons()

foreach ($buttons as $key => $button) {
     $entity_type = $button['value'];
     if (in_array($entity_type, $node_types) && !node_access('create', $entity_type)) {
       unset($buttons[$entity_type]);

And similar changes in oa_buttons_add_space_content_render().  Just take advantage of the contents of the $buttons array and don't use the $key.

2) Would be good if the title of the button was changed to "Create Discussion Post in Section Name" if multiple sections are detected with the same content type.  Otherwise it seems like you'd just get multiple "Create Discussion Post" buttons and the user wouldn't know which to select.

3) Roll an updated oa_worktracker patch that looks for oa_worktracker in the $button['values'] rather than using strpos.

**Comment by scottalan** [comment]
Sounds good. I wasn't thinking about multilingual. As far as the title, I will change it to "Create Discussion Post in Section Name", but as of now I get "Create `section_name`". I'll get these changes in. Thanks

**Comment by scottalan** [comment]
I have also updated the `command_buttons` patch so that the link is built to include the section type as well. https://drupal.org/node/2273515#comment-8818573. I also rolled a new patch for `oa_worktracker` as well. https://drupal.org/node/2273639#comment-8818547

**Pull request merged**
